# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
  - stage: Gather_data

    jobs:
      - job: 'ScrapeGit'

        strategy:
          parallel: 5

        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - script: |
            source scripts/installGithubScrapping.sh
            echo "Will scrape:"
            cat scripts/sample/sample.txt | slicer.sh $(System.JobPositionInPhase)  $(TotalJobsInPhase)
            echo
            cat scripts/sample/sample.txt | slicer.sh $(System.JobPositionInPhase)  $(TotalJobsInPhase)   |  gitReports.sh - '2 years ago' 'today'
          displayName: 'Git Scrape'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'gitReports'
            artifact: 'GitReports'
            publishLocation: 'pipeline'